/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho_voos;

import java.awt.event.ActionListener;

/**
 *
 * @author Douglas Verly
 */
public class ControleVooJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ControleVooJFrame
     */
    public ControleVooJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldnome = new javax.swing.JTextField();
        jTextFieldcpf = new javax.swing.JTextField();
        jTextFieldcodvoo = new javax.swing.JTextField();
        jTextFieldpreco = new javax.swing.JTextField();
        jTextFieldcodcompanhia = new javax.swing.JTextField();
        jTextFieldnomecompanhia = new javax.swing.JTextField();
        jTextFielddata = new javax.swing.JTextField();
        jButtonsalvar = new javax.swing.JButton();
        jButtonbuscar = new javax.swing.JButton();
        jLabelnome = new javax.swing.JLabel();
        jLabelcpf = new javax.swing.JLabel();
        jLabelcodvoo = new javax.swing.JLabel();
        jLabelpreco = new javax.swing.JLabel();
        jLabelcodcompanhia = new javax.swing.JLabel();
        jLabelnomecompanhia = new javax.swing.JLabel();
        jLabeldata = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("CPF:");

        jLabel3.setText("Cod.Voo");

        jLabel4.setText("Preço:");

        jLabel5.setText("Cod.Companhia");

        jLabel6.setText("Nome Companhia");

        jLabel7.setText("Data Mês/Ano");

        jButtonsalvar.setText("Salvar");

        jButtonbuscar.setText("Buscar");

        jLabelnome.setText("Nome");

        jLabelcpf.setText("CPF");

        jLabelcodvoo.setText("Cod.Voo");

        jLabelpreco.setText("Preço");

        jLabelcodcompanhia.setText("Cod.Companhia");

        jLabelnomecompanhia.setText("Nome.Companhia");

        jLabeldata.setText("Data Mês/Ano");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonsalvar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldcpf)
                                .addComponent(jTextFieldcodvoo)
                                .addComponent(jTextFieldpreco)
                                .addComponent(jTextFieldcodcompanhia)
                                .addComponent(jTextFieldnomecompanhia)
                                .addComponent(jTextFielddata, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)))))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonbuscar)
                    .addComponent(jLabelnome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelcpf)
                    .addComponent(jLabelcodvoo)
                    .addComponent(jLabelpreco)
                    .addComponent(jLabelcodcompanhia)
                    .addComponent(jLabelnomecompanhia)
                    .addComponent(jLabeldata))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelnome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelcpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldcodvoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelcodvoo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelpreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldcodcompanhia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelcodcompanhia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldnomecompanhia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelnomecompanhia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFielddata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeldata))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonsalvar)
                    .addComponent(jButtonbuscar))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonbuscar;
    private javax.swing.JButton jButtonsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelcodcompanhia;
    private javax.swing.JLabel jLabelcodvoo;
    private javax.swing.JLabel jLabelcpf;
    private javax.swing.JLabel jLabeldata;
    private javax.swing.JLabel jLabelnome;
    private javax.swing.JLabel jLabelnomecompanhia;
    private javax.swing.JLabel jLabelpreco;
    private javax.swing.JTextField jTextFieldcodcompanhia;
    private javax.swing.JTextField jTextFieldcodvoo;
    private javax.swing.JTextField jTextFieldcpf;
    private javax.swing.JTextField jTextFielddata;
    private javax.swing.JTextField jTextFieldnome;
    private javax.swing.JTextField jTextFieldnomecompanhia;
    private javax.swing.JTextField jTextFieldpreco;
    // End of variables declaration//GEN-END:variables

    
    public Passageiro obtemObjetoPassageiro(){
    String nome=jTextFieldnome.getText();
    int cpf=Integer.parseInt(jTextFieldcpf.getText());
    String codigovoo=jTextFieldcodvoo.getText();
    Double preco=Double.parseDouble(jTextFieldpreco.getText());
    String codigocompanhia=jTextFieldcodcompanhia.getText();
    String nomecompanhia=jTextFieldnomecompanhia.getText();
    String mesanovoo=jTextFielddata.getText();
    Passageiro p = new Passageiro(nome,cpf,codigovoo,preco,codigocompanhia,nomecompanhia,mesanovoo);
   
    return p;}
    
    public void mostrarnatela(Passageiro p){
jLabelnome.setText(p.getNomePassageiro());
jLabelcpf.setText(Integer.toString(p.getCpfPassageiro()));
jLabelcodvoo.setText(p.getCodigoVoo());
jLabelpreco.setText(Double.toString(p.getPrecoPassagem()));
jLabelcodcompanhia.setText(p.getCodigoCompanhia());
jLabelnomecompanhia.setText(p.getNomeCompanhia());
jLabeldata.setText(p.getMesAnoVoo());
}
    
    
    
public void adicionaManipuladorEventosInsere(ActionListener manipulador){
jButtonsalvar.addActionListener(manipulador);

}



}
